import { MemberRecord, SpouseRelationRecord } from '@/types/tree';

export const SAMPLE_MEMBERS_28: MemberRecord[] = [
  // --- ĐỜI 1 (2 người) ---
  {
    id: 'm-root-khoi',
    full_name: 'Nguyễn Văn Khởi',
    gender: 'male',
    life_status: 'deceased',
    birth_year: 1910,
    death_year: 1985,
    death_lunar_day: 15,
    death_lunar_month: 8,
    generation_level: 1,
    birth_order: 1,
    is_root: true,
    branch_name: 'Gốc Gia Tộc',
  },
  {
    id: 'm-root-to',
    full_name: 'Trần Thị Tổ',
    gender: 'female',
    life_status: 'deceased',
    birth_year: 1912,
    death_year: 1990,
    generation_level: 1,
    is_root: false,
    branch_name: 'Gốc Gia Tộc',
  },

  // --- ĐỜI 2: 2 Chi (4 người) ---
  // Chi 1
  {
    id: 'm-gen2-truong',
    full_name: 'Nguyễn Văn Trưởng',
    gender: 'male',
    life_status: 'deceased',
    father_id: 'm-root-khoi',
    mother_id: 'm-root-to',
    birth_year: 1935,
    death_year: 2005,
    generation_level: 2,
    birth_order: 1,
    is_root: false,
    branch_name: 'Chi 1 - Trưởng',
  },
  {
    id: 'm-gen2-hoa',
    full_name: 'Lê Thị Hoa',
    gender: 'female',
    life_status: 'deceased',
    birth_year: 1938,
    death_year: 2010,
    generation_level: 2,
    is_root: false,
    branch_name: 'Chi 1 - Trưởng',
  },
  // Chi 2
  {
    id: 'm-gen2-thu',
    full_name: 'Nguyễn Văn Thứ',
    gender: 'male',
    life_status: 'deceased',
    father_id: 'm-root-khoi',
    mother_id: 'm-root-to',
    birth_year: 1940,
    death_year: 2015,
    generation_level: 2,
    birth_order: 2,
    is_root: false,
    branch_name: 'Chi 2 - Thứ',
  },
  {
    id: 'm-gen2-lan',
    full_name: 'Phạm Thị Lan',
    gender: 'female',
    life_status: 'living',
    birth_year: 1943,
    generation_level: 2,
    is_root: false,
    branch_name: 'Chi 2 - Thứ',
  },

  // --- ĐỜI 3: 10 người ---
  // Chi 1 (5 người)
  {
    id: 'm-gen3-an',
    full_name: 'Nguyễn Văn An',
    gender: 'male',
    life_status: 'living',
    father_id: 'm-gen2-truong',
    mother_id: 'm-gen2-hoa',
    birth_year: 1962,
    generation_level: 3,
    birth_order: 1,
    is_root: false,
    branch_name: 'Chi 1 - Trưởng',
  },
  {
    id: 'm-gen3-mai-an',
    full_name: 'Hoàng Thị Mai',
    gender: 'female',
    life_status: 'living',
    birth_year: 1965,
    generation_level: 3,
    is_root: false,
    branch_name: 'Chi 1 - Trưởng',
  },
  {
    id: 'm-gen3-binh',
    full_name: 'Nguyễn Văn Bình',
    gender: 'male',
    life_status: 'living',
    father_id: 'm-gen2-truong',
    mother_id: 'm-gen2-hoa',
    birth_year: 1966,
    generation_level: 3,
    birth_order: 2,
    is_root: false,
    branch_name: 'Chi 1 - Trưởng',
  },
  {
    id: 'm-gen3-cuc',
    full_name: 'Vũ Thị Cúc',
    gender: 'female',
    life_status: 'living',
    birth_year: 1968,
    generation_level: 3,
    is_root: false,
    branch_name: 'Chi 1 - Trưởng',
  },
  {
    id: 'm-gen3-dao',
    full_name: 'Nguyễn Thị Đào',
    gender: 'female',
    life_status: 'living',
    father_id: 'm-gen2-truong',
    mother_id: 'm-gen2-hoa',
    birth_year: 1970,
    generation_level: 3,
    birth_order: 3,
    is_root: false,
    branch_name: 'Chi 1 - Trưởng',
  },

  // Chi 2 (5 người)
  {
    id: 'm-gen3-dung',
    full_name: 'Nguyễn Văn Dũng',
    gender: 'male',
    life_status: 'living',
    father_id: 'm-gen2-thu',
    mother_id: 'm-gen2-lan',
    birth_year: 1968,
    generation_level: 3,
    birth_order: 1,
    is_root: false,
    branch_name: 'Chi 2 - Thứ',
  },
  {
    id: 'm-gen3-yen',
    full_name: 'Đặng Thị Yến',
    gender: 'female',
    life_status: 'living',
    birth_year: 1970,
    generation_level: 3,
    is_root: false,
    branch_name: 'Chi 2 - Thứ',
  },
  {
    id: 'm-gen3-giang',
    full_name: 'Nguyễn Văn Giang',
    gender: 'male',
    life_status: 'living',
    father_id: 'm-gen2-thu',
    mother_id: 'm-gen2-lan',
    birth_year: 1972,
    generation_level: 3,
    birth_order: 2,
    is_root: false,
    branch_name: 'Chi 2 - Thứ',
  },
  {
    id: 'm-gen3-hong',
    full_name: 'Bùi Thị Hồng',
    gender: 'female',
    life_status: 'living',
    birth_year: 1975,
    generation_level: 3,
    is_root: false,
    branch_name: 'Chi 2 - Thứ',
  },
  {
    id: 'm-gen3-hanh',
    full_name: 'Nguyễn Thị Hạnh',
    gender: 'female',
    life_status: 'living',
    father_id: 'm-gen2-thu',
    mother_id: 'm-gen2-lan',
    birth_year: 1976,
    generation_level: 3,
    birth_order: 3,
    is_root: false,
    branch_name: 'Chi 2 - Thứ',
  },

  // --- ĐỜI 4: 12 người ---
  // Nhánh An (Chi 1):
  {
    id: 'm-gen4-tuan',
    full_name: 'Nguyễn Văn Tuấn',
    gender: 'male',
    life_status: 'living',
    father_id: 'm-gen3-an',
    mother_id: 'm-gen3-mai-an',
    birth_year: 1990,
    generation_level: 4,
    birth_order: 1,
    is_root: false,
    branch_name: 'Chi 1 - Trưởng',
  },
  {
    id: 'm-gen4-kien',
    full_name: 'Nguyễn Văn Kiên',
    gender: 'male',
    life_status: 'living',
    father_id: 'm-gen3-an',
    mother_id: 'm-gen3-mai-an',
    birth_year: 1993,
    generation_level: 4,
    birth_order: 2,
    is_root: false,
    branch_name: 'Chi 1 - Trưởng',
  },
  {
    id: 'm-gen4-thao',
    full_name: 'Đỗ Thị Thảo',
    gender: 'female',
    life_status: 'living',
    birth_year: 1995,
    generation_level: 4,
    is_root: false,
    branch_name: 'Chi 1 - Trưởng',
  },

  // Nhánh Bình (Chi 1):
  {
    id: 'm-gen4-long',
    full_name: 'Nguyễn Văn Long',
    gender: 'male',
    life_status: 'living',
    father_id: 'm-gen3-binh',
    mother_id: 'm-gen3-cuc',
    birth_year: 1994,
    generation_level: 4,
    birth_order: 1,
    is_root: false,
    branch_name: 'Chi 1 - Trưởng',
  },
  {
    id: 'm-gen4-linh',
    full_name: 'Trịnh Thị Linh',
    gender: 'female',
    life_status: 'living',
    birth_year: 1996,
    generation_level: 4,
    is_root: false,
    branch_name: 'Chi 1 - Trưởng',
  },
  {
    id: 'm-gen4-nga',
    full_name: 'Nguyễn Thị Nga',
    gender: 'female',
    life_status: 'living',
    father_id: 'm-gen3-binh',
    mother_id: 'm-gen3-cuc',
    birth_year: 1998,
    generation_level: 4,
    birth_order: 2,
    is_root: false,
    branch_name: 'Chi 1 - Trưởng',
  },

  // Nhánh Dũng (Chi 2):
  {
    id: 'm-gen4-mai-noi-toc',
    full_name: 'Nguyễn Thị Mai',
    gender: 'female',
    life_status: 'living',
    father_id: 'm-gen3-dung',
    mother_id: 'm-gen3-yen',
    birth_year: 1992,
    generation_level: 4,
    birth_order: 1,
    is_root: false,
    branch_name: 'Chi 2 - Thứ',
  },
  {
    id: 'm-gen4-nam',
    full_name: 'Nguyễn Văn Nam',
    gender: 'male',
    life_status: 'living',
    father_id: 'm-gen3-dung',
    mother_id: 'm-gen3-yen',
    birth_year: 1995,
    generation_level: 4,
    birth_order: 2,
    is_root: false,
    branch_name: 'Chi 2 - Thứ',
  },
  {
    id: 'm-gen4-oanh',
    full_name: 'Ngô Thị Oanh',
    gender: 'female',
    life_status: 'living',
    birth_year: 1997,
    generation_level: 4,
    is_root: false,
    branch_name: 'Chi 2 - Thứ',
  },

  // Nhánh Giang (Chi 2):
  {
    id: 'm-gen4-phong',
    full_name: 'Nguyễn Văn Phong',
    gender: 'male',
    life_status: 'living',
    father_id: 'm-gen3-giang',
    mother_id: 'm-gen3-hong',
    birth_year: 1998,
    generation_level: 4,
    birth_order: 1,
    is_root: false,
    branch_name: 'Chi 2 - Thứ',
  },
  {
    id: 'm-gen4-quynh',
    full_name: 'Nguyễn Thị Quỳnh',
    gender: 'female',
    life_status: 'living',
    father_id: 'm-gen3-giang',
    mother_id: 'm-gen3-hong',
    birth_year: 2001,
    generation_level: 4,
    birth_order: 2,
    is_root: false,
    branch_name: 'Chi 2 - Thứ',
  },
  {
    id: 'm-gen4-hung',
    full_name: 'Trần Văn Hùng',
    gender: 'male',
    life_status: 'living',
    birth_year: 1999,
    generation_level: 4,
    is_root: false,
    branch_name: 'Chi 2 - Thứ',
  },
];

export const SAMPLE_SPOUSE_RELATIONS: SpouseRelationRecord[] = [
  // Đời 1
  { id: 'rel-root', member_a_id: 'm-root-khoi', member_b_id: 'm-root-to', marriage_order: 1 },

  // Đời 2
  { id: 'rel-gen2-c1', member_a_id: 'm-gen2-truong', member_b_id: 'm-gen2-hoa', marriage_order: 1 },
  { id: 'rel-gen2-c2', member_a_id: 'm-gen2-thu', member_b_id: 'm-gen2-lan', marriage_order: 1 },

  // Đời 3
  { id: 'rel-gen3-an', member_a_id: 'm-gen3-an', member_b_id: 'm-gen3-mai-an', marriage_order: 1 },
  { id: 'rel-gen3-binh', member_a_id: 'm-gen3-binh', member_b_id: 'm-gen3-cuc', marriage_order: 1 },
  { id: 'rel-gen3-dung', member_a_id: 'm-gen3-dung', member_b_id: 'm-gen3-yen', marriage_order: 1 },
  { id: 'rel-gen3-giang', member_a_id: 'm-gen3-giang', member_b_id: 'm-gen3-hong', marriage_order: 1 },

  // Đời 4 (Cặp hôn nhân nội tộc: Tuấn Chi 1 + Mai Chi 2)
  { id: 'rel-gen4-noi-toc', member_a_id: 'm-gen4-tuan', member_b_id: 'm-gen4-mai-noi-toc', marriage_order: 1 },
  { id: 'rel-gen4-kien', member_a_id: 'm-gen4-kien', member_b_id: 'm-gen4-thao', marriage_order: 1 },
  { id: 'rel-gen4-long', member_a_id: 'm-gen4-long', member_b_id: 'm-gen4-linh', marriage_order: 1 },
  { id: 'rel-gen4-nam', member_a_id: 'm-gen4-nam', member_b_id: 'm-gen4-oanh', marriage_order: 1 },
  { id: 'rel-gen4-quynh', member_a_id: 'm-gen4-quynh', member_b_id: 'm-gen4-hung', marriage_order: 1 },
];
